---
applications:

- name: zx0000-common
  memory: 1500M
  timeout: 300
  random-route: true
  path: application/target/zx0000-common-application.jar
  buildpacks:
    - sap_java_buildpack
  env:
     # warに変更したためtomcatに変更
    TARGET_RUNTIME: main
    # logback-spring.xmlに定義されたプロファイル名を指定する
    SPRING_PROFILES_ACTIVE: 'cloud'
    JBP_CONFIG_SAPJVM_MEMORY_SIZES: 'metaspace:128m..'
services:
  - addondb_hdi
resources:
  - name: addondb_hdi
    type: com.sap.xs.hdi-container
    parameters:
      config:
        schema: ADDONDB
      properties:
        hdi-container-name: ${service-name}
#  - my-application-logs
#  - my-xsuaa
#  - my-destination
#  - my-connectivity

spring:
  datasource:
    name: jdbc/DefaultDB
    type: javax.sql.DataSource
    factory: com.sap.xs.jdbc.datasource.tomcat.TomcatDataSourceFactory
    service: addondb_hdi
    driverClassName:  com.sap.db.jdbc.Driver
